## Tensorflow 2 安装

In [5]:
# %% Tensorflow 版本
import tensorflow as tf

tf.__version__

'2.3.0'

## Eager Execution

由 **Graph Execution** 重构为 **Eager Execution** ，极大程度降低 Tensorflow 使用门槛。

In [6]:
# %% 2.x 张量值
c = tf.Variable([[1, 2], [3, 4]])
c

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [7]:
# %% 获得 Tensorflow 张量的 NumPy 数组表示
c.numpy()

array([[1, 2],
       [3, 4]])

In [8]:
# %% 即时数学计算
c + c

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 4],
       [6, 8]])>

In [9]:
# %% 自动梯度追踪
w = tf.Variable([[1.0]])
with tf.GradientTape() as tape:
    loss = w * w
grad = tape.gradient(loss, w)
grad

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[2.]], dtype=float32)>

## Tensorflow Keras

1.x 版本中的 `tf.layers` 和 `tf.contrib` 被移除，引入 `tf.keras` 。