<h1>目录<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#NumPy-数组类型" data-toc-modified-id="NumPy-数组类型-1">NumPy 数组类型</a></span></li><li><span><a href="#NumPy-数组生成" data-toc-modified-id="NumPy-数组生成-2">NumPy 数组生成</a></span><ul class="toc-item"><li><span><a href="#列表或元组转换" data-toc-modified-id="列表或元组转换-2.1">列表或元组转换</a></span></li><li><span><a href="#arange方法创建" data-toc-modified-id="arange方法创建-2.2"><code>arange</code>方法创建</a></span></li><li><span><a href="#linspace方法创建" data-toc-modified-id="linspace方法创建-2.3"><code>linspace</code>方法创建</a></span></li><li><span><a href="#ones方法创建" data-toc-modified-id="ones方法创建-2.4"><code>ones</code>方法创建</a></span></li><li><span><a href="#zeros方法创建" data-toc-modified-id="zeros方法创建-2.5"><code>zeros</code>方法创建</a></span></li><li><span><a href="#eye方法创建" data-toc-modified-id="eye方法创建-2.6"><code>eye</code>方法创建</a></span></li><li><span><a href="#从已知数据创建" data-toc-modified-id="从已知数据创建-2.7">从已知数据创建</a></span></li><li><span><a href="#ndarray属性" data-toc-modified-id="ndarray属性-2.8"><code>ndarray</code>属性</a></span></li></ul></li><li><span><a href="#数组维度和形状" data-toc-modified-id="数组维度和形状-3">数组维度和形状</a></span></li><li><span><a href="#数组基本操作" data-toc-modified-id="数组基本操作-4">数组基本操作</a></span><ul class="toc-item"><li><span><a href="#重设形状" data-toc-modified-id="重设形状-4.1">重设形状</a></span></li><li><span><a href="#数组展开" data-toc-modified-id="数组展开-4.2">数组展开</a></span></li><li><span><a href="#轴移动" data-toc-modified-id="轴移动-4.3">轴移动</a></span></li><li><span><a href="#轴交换" data-toc-modified-id="轴交换-4.4">轴交换</a></span></li><li><span><a href="#数组转置" data-toc-modified-id="数组转置-4.5">数组转置</a></span></li><li><span><a href="#维度改变" data-toc-modified-id="维度改变-4.6">维度改变</a></span></li><li><span><a href="#类型转换" data-toc-modified-id="类型转换-4.7">类型转换</a></span></li><li><span><a href="#数组连接" data-toc-modified-id="数组连接-4.8">数组连接</a></span></li><li><span><a href="#数组堆叠" data-toc-modified-id="数组堆叠-4.9">数组堆叠</a></span></li><li><span><a href="#拆分" data-toc-modified-id="拆分-4.10">拆分</a></span></li><li><span><a href="#删除" data-toc-modified-id="删除-4.11">删除</a></span></li><li><span><a href="#数组插入" data-toc-modified-id="数组插入-4.12">数组插入</a></span></li><li><span><a href="#附加" data-toc-modified-id="附加-4.13">附加</a></span></li><li><span><a href="#翻转数组" data-toc-modified-id="翻转数组-4.14">翻转数组</a></span></li><li><span><a href="#NumPy-随机数" data-toc-modified-id="NumPy-随机数-4.15">NumPy 随机数</a></span></li><li><span><a href="#概率密度分布" data-toc-modified-id="概率密度分布-4.16">概率密度分布</a></span></li></ul></li><li><span><a href="#数学函数" data-toc-modified-id="数学函数-5">数学函数</a></span><ul class="toc-item"><li><span><a href="#三角函数" data-toc-modified-id="三角函数-5.1">三角函数</a></span></li><li><span><a href="#双曲函数" data-toc-modified-id="双曲函数-5.2">双曲函数</a></span></li><li><span><a href="#数值修约" data-toc-modified-id="数值修约-5.3">数值修约</a></span></li><li><span><a href="#求和、求积、差分" data-toc-modified-id="求和、求积、差分-5.4">求和、求积、差分</a></span></li><li><span><a href="#指数和对数" data-toc-modified-id="指数和对数-5.5">指数和对数</a></span></li><li><span><a href="#算术运算" data-toc-modified-id="算术运算-5.6">算术运算</a></span></li><li><span><a href="#矩阵和向量积" data-toc-modified-id="矩阵和向量积-5.7">矩阵和向量积</a></span></li><li><span><a href="#数学运算" data-toc-modified-id="数学运算-5.8">数学运算</a></span></li><li><span><a href="#线性代数" data-toc-modified-id="线性代数-5.9">线性代数</a></span></li></ul></li></ul></div>

In [1]:
# %% 检查 Python 版本
from sys import version
print(version)

3.8.12 (default, Oct 12 2021, 03:01:40) [MSC v.1916 64 bit (AMD64)]


## NumPy 数组类型

In [2]:
import numpy as np

In [3]:
a = np.array([1.1, 2.2, 3.3], dtype=np.float64)
a, a.dtype

(array([1.1, 2.2, 3.3]), dtype('float64'))

In [4]:
# %% 类型转换
a.astype(int).dtype

dtype('int32')

此处由于所选数值较小，Python 3.8 中选用了 `int32` 进行存储。

## NumPy 数组生成

### 列表或元组转换

```python
numpy.array(object, dtype=None, copy=True, order=None, subok=False, ndmin=0)
```

In [5]:
np.array([[1, 2, 3], [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
np.array([(1, 2), (3, 4), (5, 6)])

array([[1, 2],
       [3, 4],
       [5, 6]])

### `arange`方法创建

```python
numpy.arange(start, stop, step, dtype=None)
```

In [7]:
np.arange(3, 7, 0.5, dtype='float32')

array([3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5], dtype=float32)

### `linspace`方法创建

```python
numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
```

In [8]:
np.linspace(0, 10, 10, endpoint=True)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [9]:
np.linspace(0, 10, 10, endpoint=False)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

### `ones`方法创建

```python
numpy.ones(shape, dtype=None, order='C')
```

In [10]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

### `zeros`方法创建

In [11]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

### `eye`方法创建

```python
numpy.eye(N, M=None, k=0, dtype=<type 'float'>)
```

In [12]:
np.eye(5, 4, 3)

array([[0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### 从已知数据创建

In [13]:
from operator import add

np.fromfunction(add, (5, 4))

array([[0., 1., 2., 3.],
       [1., 2., 3., 4.],
       [2., 3., 4., 5.],
       [3., 4., 5., 6.],
       [4., 5., 6., 7.]])

In [14]:
from itertools import count, islice

c = count()
np.fromiter(islice(c, 1, 15), dtype=np.int_)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [15]:
np.fromstring('1, 2', dtype=int, sep=',')

array([1, 2])

### `ndarray`属性

In [16]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
a.T, a.T == a.transpose()

(array([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]]),
 array([[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]]))

In [18]:
a.dtype

dtype('int32')

In [19]:
a.imag, a.real

(array([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]),
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]))

In [20]:
a.size, a.itemsize

(9, 4)

In [21]:
a.nbytes, a.ndim

(36, 2)

In [22]:
a.shape, a.strides

((3, 3), (12, 4))

## 数组维度和形状

In [23]:
one = np.array([7, 2, 9, 10])
two = np.array([[5.2, 3.0, 4.5], [9.1, 0.1, 0.3]])
three = np.ones(shape=(4, 3, 2), dtype='int')

In [24]:
one.shape, two.shape, three.shape

((4,), (2, 3), (4, 3, 2))

## 数组基本操作

### 重设形状

In [25]:
np.arange(10).reshape((5, 2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

### 数组展开

In [26]:
a = np.arange(10).reshape((2, 5))
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [27]:
np.ravel(a)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
np.ravel(a, order='F')

array([0, 5, 1, 6, 2, 7, 3, 8, 4, 9])

### 轴移动

In [29]:
a = np.ones((1, 2, 3))
np.moveaxis(a, 0, -1)

array([[[1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.]]])

In [30]:
a.shape, np.moveaxis(a, 0, -1).shape

((1, 2, 3), (2, 3, 1))

### 轴交换

In [31]:
a = np.ones((1, 4, 3))
np.swapaxes(a, 0, 2)

array([[[1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.]]])

### 数组转置

In [32]:
a = np.arange(4).reshape(2, 2)
np.transpose(a)

array([[0, 2],
       [1, 3]])

### 维度改变

In [33]:
print(np.atleast_1d([1, 2, 3]))
print(np.atleast_2d([4, 5, 6]))
print(np.atleast_3d([7, 8, 9]))

[1 2 3]
[[4 5 6]]
[[[7]
  [8]
  [9]]]


### 类型转换

In [34]:
a = np.arange(4).reshape(2, 2)
np.asarray(a, dtype='float32', order='F')

array([[0., 1.],
       [2., 3.]], dtype=float32)

In [35]:
np.asanyarray(a, dtype='float32', order='F')

array([[0., 1.],
       [2., 3.]], dtype=float32)

In [36]:
np.asmatrix(a, dtype='float32')

matrix([[0., 1.],
        [2., 3.]], dtype=float32)

In [37]:
np.asfarray(a)

array([[0., 1.],
       [2., 3.]])

In [38]:
np.asarray_chkfinite(a)

array([[0, 1],
       [2, 3]])

In [39]:
np.asscalar(a[0, 1])

C:\Users\DRAGON~1\AppData\Local\Temp/ipykernel_10148/3547684317.py:1: DeprecationWarning: np.asscalar(a) is deprecated since NumPy v1.16, use a.item() instead
  np.asscalar(a[0, 1])


1

### 数组连接

In [40]:
a = np.array([[1, 2], [3, 4], [5, 6]])
b = np.array([[7, 8], [9, 10]])
c = np.array([[11, 12]])
np.concatenate((a, b, c), axis=0)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [41]:
a = np.array([[1, 2], [3, 4], [5, 6]])
b = np.array([[7, 8, 9]])
np.concatenate((a, b.T), axis=1)

array([[1, 2, 7],
       [3, 4, 8],
       [5, 6, 9]])

### 数组堆叠

In [42]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.stack((a, b))

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
np.column_stack((a, b))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [44]:
np.hstack((a, b))

array([1, 2, 3, 4, 5, 6])

In [45]:
np.vstack((a, b))

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
np.dstack((a, b))

array([[[1, 4],
        [2, 5],
        [3, 6]]])

### 拆分

In [47]:
a = np.arange(10)
np.split(a, 5)

[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]

In [48]:
a = np.arange(10).reshape(2, 5)
np.split(a, 2)

[array([[0, 1, 2, 3, 4]]), array([[5, 6, 7, 8, 9]])]

### 删除

In [49]:
a = np.arange(12).reshape(3, 4)
np.delete(a, 2, 1)

array([[ 0,  1,  3],
       [ 4,  5,  7],
       [ 8,  9, 11]])

In [50]:
np.delete(a, 2, 0)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

### 数组插入

In [51]:
a = np.arange(12).reshape(3, 4)
b = np.arange(4)
np.insert(a, 2, b, 0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

### 附加

`append`方法默认将数组展平后添加

In [52]:
a = np.arange(6).reshape(2, 3)
b = np.arange(3)
np.append(a, b)

array([0, 1, 2, 3, 4, 5, 0, 1, 2])

In [53]:
a = np.arange(10)
a.resize(2, 5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

`resize`对 NumPy 数组自身有副作用，返回其自身；`reshape`对 NumPy 数组无副作用，返回新副本。

### 翻转数组

In [54]:
a = np.arange(16).reshape(4, 4)
print(np.fliplr(a))
print(np.flipud(a))

[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]
 [15 14 13 12]]
[[12 13 14 15]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


### NumPy 随机数

In [55]:
np.random.rand(2, 5)

array([[0.94488409, 0.77111816, 0.24203138, 0.93315384, 0.05961138],
       [0.28819382, 0.72878903, 0.28301255, 0.18181852, 0.2057197 ]])

In [56]:
np.random.randn(1, 10)

array([[ 0.66448558, -0.45625441,  0.42767817, -0.05356481,  0.84870624,
         0.88121481, -1.06696916, -0.25146217,  1.62386441,  0.37541806]])

`rand`为 $[0, 1)$ 之间的均匀分布，`randn`为 $\mathcal{N}(0, 1)$ 标准正态分布。

In [57]:
np.random.randint(2, 5, 10)

array([3, 3, 2, 2, 4, 4, 2, 3, 4, 4])

In [58]:
np.random.random_sample(10)

array([0.1682215 , 0.68361162, 0.42920566, 0.95404468, 0.63166446,
       0.30586959, 0.39183177, 0.30040989, 0.07631003, 0.28052101])

In [59]:
np.random.choice(10, 5)

array([2, 6, 2, 1, 1])

### 概率密度分布

- `numpy.random.beta(a，b，size)`：从 Beta 分布中生成随机数。
- `numpy.random.binomial(n, p, size)`：从二项分布中生成随机数。
- `numpy.random.chisquare(df，size)`：从卡方分布中生成随机数。
- `numpy.random.dirichlet(alpha，size)`：从 Dirichlet 分布中生成随机数。
- `numpy.random.exponential(scale，size)`：从指数分布中生成随机数。
- `numpy.random.f(dfnum，dfden，size)`：从 F 分布中生成随机数。
- `numpy.random.gamma(shape，scale，size)`：从 Gamma 分布中生成随机数。
- `numpy.random.geometric(p，size)`：从几何分布中生成随机数。
- `numpy.random.gumbel(loc，scale，size)`：从 Gumbel 分布中生成随机数。
- `numpy.random.hypergeometric(ngood, nbad, nsample, size)`：从超几何分布中生成随机数。
- `numpy.random.laplace(loc，scale，size)`：从拉普拉斯双指数分布中生成随机数。
- `numpy.random.logistic(loc，scale，size)`：从逻辑分布中生成随机数。
- `numpy.random.lognormal(mean，sigma，size)`：从对数正态分布中生成随机数。
- `numpy.random.logseries(p，size)`：从对数系列分布中生成随机数。
- `numpy.random.multinomial(n，pvals，size)`：从多项分布中生成随机数。
- `numpy.random.multivariate_normal(mean, cov, size)`：从多变量正态分布绘制随机样本。
- `numpy.random.negative_binomial(n, p, size)`：从负二项分布中生成随机数。
- `numpy.random.noncentral_chisquare(df，nonc，size)`：从非中心卡方分布中生成随机数。
- `numpy.random.noncentral_f(dfnum, dfden, nonc, size)`：从非中心 F 分布中抽取样本。
- `numpy.random.normal(loc，scale，size)`：从正态分布绘制随机样本。
- `numpy.random.pareto(a，size)`：从具有指定形状的 Pareto II 或 Lomax 分布中生成随机数。
- `numpy.random.poisson(lam，size)`：从泊松分布中生成随机数。
- `numpy.random.power(a，size)`：从具有正指数 a-1 的功率分布中在 0，1 中生成随机数。
- `numpy.random.rayleigh(scale，size)`：从瑞利分布中生成随机数。
- `numpy.random.standard_cauchy(size)`：从标准 Cauchy 分布中生成随机数。
- `numpy.random.standard_exponential(size)`：从标准指数分布中生成随机数。
- `numpy.random.standard_gamma(shape，size)`：从标准 Gamma 分布中生成随机数。
- `numpy.random.standard_normal(size)`：从标准正态分布中生成随机数。
- `numpy.random.standard_t(df，size)`：从具有 df 自由度的标准学生 t 分布中生成随机数。
- `numpy.random.triangular(left，mode，right，size)`：从三角分布中生成随机数。
- `numpy.random.uniform(low，high，size)`：从均匀分布中生成随机数。
- `numpy.random.vonmises(mu，kappa，size)`：从 von Mises 分布中生成随机数。
- `numpy.random.wald(mean，scale，size)`：从 Wald 或反高斯分布中生成随机数。
- `numpy.random.weibull(a，size)`：从威布尔分布中生成随机数。
- `numpy.random.zipf(a，size)`：从 Zipf 分布中生成随机数。

## 数学函数

### 三角函数

In [60]:
np.sin(np.pi / 6)

0.49999999999999994

In [61]:
np.cos(np.pi / 3)

0.5000000000000001

In [62]:
np.tan(np.pi / 4)

0.9999999999999999

In [63]:
np.rad2deg(np.arcsin(0.5))

30.000000000000004

In [64]:
np.rad2deg(np.arccos(0.5))

60.00000000000001

In [65]:
np.rad2deg(np.arctan(1))

45.0

In [66]:
np.hypot(5, 12)

13.0

### 双曲函数

- `numpy.sinh(x)`：双曲正弦。
- `numpy.cosh(x)`：双曲余弦。
- `numpy.tanh(x)`：双曲正切。
- `numpy.arcsinh(x)`：反双曲正弦。
- `numpy.arccosh(x)`：反双曲余弦。
- `numpy.arctanh(x)`：反双曲正切。

### 数值修约

In [67]:
a = np.random.randn(5)
a

array([ 1.22110433,  0.91541637,  0.11159647,  0.86510554, -0.60427453])

In [68]:
np.around(a)

array([ 1.,  1.,  0.,  1., -1.])

In [69]:
np.round_(a)

array([ 1.,  1.,  0.,  1., -1.])

In [70]:
np.rint(a)

array([ 1.,  1.,  0.,  1., -1.])

In [71]:
np.fix(a)

array([ 1.,  0.,  0.,  0., -0.])

In [72]:
np.floor(a)

array([ 1.,  0.,  0.,  0., -1.])

In [73]:
np.ceil(a)

array([ 2.,  1.,  1.,  1., -0.])

In [74]:
np.trunc(a)

array([ 1.,  0.,  0.,  0., -0.])

### 求和、求积、差分

In [75]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
np.prod(a)

0

In [77]:
np.sum(a)

45

- `numpy.nanprod(a, axis, dtype, keepdims)`：返回指定轴上的数组元素的乘积, 将 NaN 视作 1。
- `numpy.nansum(a, axis, dtype, keepdims)`：返回指定轴上的数组元素的总和, 将 NaN 视作 0。
- `numpy.cumprod(a, axis, dtype)`：返回沿给定轴的元素的累积乘积。
- `numpy.cumsum(a, axis, dtype)`：返回沿给定轴的元素的累积总和。
- `numpy.nancumprod(a, axis, dtype)`：返回沿给定轴的元素的累积乘积, 将 NaN 视作 1。
- `numpy.nancumsum(a, axis, dtype)`：返回沿给定轴的元素的累积总和, 将 NaN 视作 0。

In [78]:
np.diff(a)

array([1, 1, 1, 1, 1, 1, 1, 1, 1])

In [79]:
np.ediff1d(a)

array([1, 1, 1, 1, 1, 1, 1, 1, 1])

In [80]:
np.gradient(a)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

- `numpy.cross(a, b, axisa, axisb, axisc, axis)`：返回两个(数组）向量的叉积。

In [81]:
np.trapz(a)

40.5

### 指数和对数

- `numpy.exp(x)`：计算输入数组中所有元素的自然指数。
- `numpy.log(x)`：计算自然对数。
- `numpy.log10(x)`：计算常用对数（以 $10$ 为底）。
- `numpy.log2(x)`：计算二进制对数。

### 算术运算

In [82]:
a = np.random.randint(0, 10, 5).astype('float32')
b = np.random.randint(0, 10, 5).astype('float32')
a, b

(array([9., 6., 4., 6., 5.], dtype=float32),
 array([9., 1., 9., 9., 9.], dtype=float32))

In [83]:
np.add(a, b)

array([18.,  7., 13., 15., 14.], dtype=float32)

In [84]:
np.reciprocal(b)

array([0.11111111, 1.        , 0.11111111, 0.11111111, 0.11111111],
      dtype=float32)

In [85]:
np.negative(a)

array([-9., -6., -4., -6., -5.], dtype=float32)

In [86]:
np.multiply(a, b)

array([81.,  6., 36., 54., 45.], dtype=float32)

In [87]:
np.divide(a, b)

array([1.        , 6.        , 0.44444445, 0.6666667 , 0.5555556 ],
      dtype=float32)

In [88]:
np.power(a, b)

array([3.8742048e+08, 6.0000000e+00, 2.6214400e+05, 1.0077696e+07,
       1.9531250e+06], dtype=float32)

In [89]:
np.subtract(a, b)

array([ 0.,  5., -5., -3., -4.], dtype=float32)

In [90]:
np.fmod(a, b)

array([0., 0., 4., 6., 5.], dtype=float32)

In [91]:
np.mod(a, b)

array([0., 0., 4., 6., 5.], dtype=float32)

In [92]:
np.modf(a)

(array([0., 0., 0., 0., 0.], dtype=float32),
 array([9., 6., 4., 6., 5.], dtype=float32))

In [93]:
np.remainder(a, b)

array([0., 0., 4., 6., 5.], dtype=float32)

### 矩阵和向量积

In [94]:
a = np.matrix(((1, 2, 3), (4, 5, 6)))
b = np.matrix([[2, 2], [3, 3], [4, 4]])
np.dot(a, b)  # 矩阵点积

matrix([[20, 20],
        [47, 47]])

In [95]:
np.vdot(a, b)  # 向量点积

matrix([[2]])

- `numpy.inner(a, b)`：求解两个数组的内积。

In [96]:
np.outer(a, b)  # 向量外积

array([[ 2,  2,  3,  3,  4,  4],
       [ 4,  4,  6,  6,  8,  8],
       [ 6,  6,  9,  9, 12, 12],
       [ 8,  8, 12, 12, 16, 16],
       [10, 10, 15, 15, 20, 20],
       [12, 12, 18, 18, 24, 24]])

- `numpy.tensordot(a, b)`：求解张量点积。

In [97]:
np.kron(a, b)  # Kronecker 乘积

matrix([[ 2,  2,  4,  4,  6,  6],
        [ 3,  3,  6,  6,  9,  9],
        [ 4,  4,  8,  8, 12, 12],
        [ 8,  8, 10, 10, 12, 12],
        [12, 12, 15, 15, 18, 18],
        [16, 16, 20, 20, 24, 24]])

### 数学运算

- `numpy.angle(z, deg)`：返回复参数的角度。
- `numpy.real(val)`：返回数组元素的实部。
- `numpy.imag(val)`：返回数组元素的虚部。
- `numpy.conj(x)`：按元素方式返回共轭复数。
- `numpy.convolve(a, v, mode)`：返回线性卷积。
- `numpy.sqrt(x)`：平方根。
- `numpy.cbrt(x)`：立方根。
- `numpy.square(x)`：平方。
- `numpy.absolute(x)`：绝对值, 可求解复数。
- `numpy.fabs(x)`：绝对值。
- `numpy.sign(x)`：符号函数。
- `numpy.maximum(x1, x2)`：最大值。
- `numpy.minimum(x1, x2)`：最小值。
- `numpy.nan_to_num(x)`：用 0 替换 NaN。
- `numpy.interp(x, xp, fp, left, right, period)`：线性插值。

### 线性代数

- `numpy.linalg.cholesky(a)`：Cholesky 分解。
- `numpy.linalg.qr(a ,mode)`：计算矩阵的 QR 因式分解。
- `numpy.linalg.svd(a ,full_matrices,compute_uv)`：奇异值分解。
- `numpy.linalg.eig(a)`：计算正方形数组的特征值和右特征向量。
- `numpy.linalg.eigh(a, UPLO)`：返回 Hermitian 或对称矩阵的特征值和特征向量。
- `numpy.linalg.eigvals(a)`：计算矩阵的特征值。
- `numpy.linalg.eigvalsh(a, UPLO)`：计算 Hermitian 或真实对称矩阵的特征值。
- `numpy.linalg.norm(x ,ord,axis,keepdims)`：计算矩阵或向量范数。
- `numpy.linalg.cond(x ,p)`：计算矩阵的条件数。
- `numpy.linalg.det(a)`：计算数组的行列式。
- `numpy.linalg.matrix_rank(M ,tol)`：使用奇异值分解方法返回秩。
- `numpy.linalg.slogdet(a)`：计算数组的行列式的符号和自然对数。
- `numpy.trace(a ,offset,axis1,axis2,dtype,out)`：沿数组的对角线返回总和。
- `numpy.linalg.solve(a, b)`：求解线性矩阵方程或线性标量方程组。
- `numpy.linalg.tensorsolve(a, b ,axes)`：为 x 解出张量方程 a x = b
- `numpy.linalg.lstsq(a, b ,rcond)`：将最小二乘解返回到线性矩阵方程。
- `numpy.linalg.inv(a)`：计算逆矩阵。
- `numpy.linalg.pinv(a ,rcond)`：计算矩阵的（Moore-Penrose）伪逆。
- `numpy.linalg.tensorinv(a ,ind)`：计算 N 维数组的逆。